POST http://localhost:4001/api/auth/register
Content-Type: application/json,*/*

{
    "email": "admin@gmail.com",
    "password":"123456",
}

### register

POST http://localhost:4001/api/auth/login
Content-Type: application/json,*/*

{
    "email": "admin@gmail.com",
    "password":"123456",
}

### login

GET http://localhost:4001/api/auth/1c18e0f0-bcad-11ed-9e1f-3d4c6c7bfb81
Content-Type: application/json,*/*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFjMThlMGYwLWJjYWQtMTFlZC05ZTFmLTNkNGM2YzdiZmI4MSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjc4MTY5NzY1fQ.39TZyD4sglpdOc30VLoMB1ab4r9RS5H-cZxlqEoC9Pg"

### get user by id